{"cells":[{"metadata":{"id":"view-in-github","colab_type":"text","slideshow":{"slide_type":"skip"}},"cell_type":"markdown","source":"<a href=\"https://colab.research.google.com/github/thfruchart/tnsi/blob/main/15/Pb_ARRET.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"},{"metadata":{"id":"AM0yGHUZgzT8","slideshow":{"slide_type":"slide"}},"cell_type":"markdown","source":"# Le problème de l'arrêt"},{"metadata":{"id":"OZvovDqhg1_Q","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Un programme peut toujours être écrit sous forme d'une **fonction**, qui prend un paramètre (éventuellement un tuple si on a besoin de plusieurs paramètres!).\n\nSupposons qu'il existe un programme permettant de **tester si l'exécution d'un programme s'arrête ou non**. \n\nEn python, cela reviendrait à définir une fonction **`arret(f,x)`** ayant la spécification suivante :"},{"metadata":{"id":"ITQadrq6gyjp","slideshow":{"slide_type":"fragment"},"trusted":false},"cell_type":"code","source":"def arret(f,x):\n    '''renvoie True si l'exécution de f(x) s'arrête\n    renvoie False sinon'''\n","execution_count":null,"outputs":[]},{"metadata":{"id":"N36c6jevhXT1","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Est-il possible d'implémenter une telle fonction ?\n\nSi c'était possible, on pourrait alors programmer une autre fonction `fou(f)` qui fait appel à la fonction  `boucle_infinie()`"},{"metadata":{"id":"D4tRYuVjhfqG","slideshow":{"slide_type":"subslide"},"trusted":false},"cell_type":"code","source":"def boucle_infinie():\n    x = 1\n    while x == 1:\n        x = 1\n\n\ndef fou(f):\n    if arret(f,f):\n        boucle_infinie()\n    else : \n        print(\"Le programme est terminé\")","execution_count":null,"outputs":[]},{"metadata":{"id":"jIbR-rD0hv9K","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Question : \n\nsi on exécute `fou(fou)`, est-ce que l'exécution termine ? \n```python\ndef fou(f):\n    if arret(f,f):\n        boucle_infinie()\n    else : \n        print(\"Le programme est terminé\")\n```\n* si `fou(fou)` termine, alors \n  * `arret(fou,fou)` renvoie `True`, donc :\n  * dans le code de fou, la condition `arret(f,f)` est évaluée à `True`, donc :\n  * la commande `boucle_infinie()` est exécutée, donc :\n  * `fou(fou)` ne termine jamais\n  * impossible !"},{"metadata":{"slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"MAIS\n```python\ndef fou(f):\n    if arret(f,f):\n        boucle_infinie()\n    else : \n        print(\"Le programme est terminé\")\n```\n\n* si `fou(fou)` ne termine pas, alors \n  * `arret(fou,fou)` renvoie `False`,\n  * dans le code de fou, la condition `arret(f,f)` est évaluée à `False`, \n  * la commande `print(\"Le programme est terminé\")` est exécutée,\n  * `fou(fou)` termine \n  * impossible aussi!"},{"metadata":{"id":"lkO7t6UMiyyY","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"La seule conclusion logique est que la fonction `fou` ne peut pas être programmée!\n\nOr on l'a programmée... mais en supposant qu'il existait une fonction `arret`.\n\nLa conclusion est donc que cette fonction `arret` ne peut pas être implémentée !"},{"metadata":{"slideshow":{"slide_type":"fragment"}},"cell_type":"markdown","source":"###  On dit que le problème de l'arrêt est indécidable."}],"metadata":{"colab":{"name":"Chap15_Pb_ARRET.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyOKB1dMOoRiU/LsVkcHnb0Y","include_colab_link":true},"kernelspec":{"name":"python3","display_name":"Python 3"},"celltoolbar":"Diaporama"},"nbformat":4,"nbformat_minor":2}